#!/usr/bin/env php
<?php

require __DIR__ . "/vendor/autoload.php";

use Symfony\Component\Config\FileLocator;
use Symfony\Component\Console\Application;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;

$containerBuilder = new ContainerBuilder();
$loader = new YamlFileLoader($containerBuilder, new FileLocator(__DIR__));
$loader->load("config/services.yaml");

$dump = new Chronis\Command\DumpCommand();
$dump->setContainer($containerBuilder);

$app = new Application("A crontab generator using natural language expressions.", "0.2.0");
$app->add($dump);
$app->run();
