parameters:
    version: 0.3.0

services:
    config_parser:
        class: Chronis\Service\ConfigurationParserService

    crontab_generator:
        class: Chronis\Service\CrontabGeneratorService
        arguments:
            - "@config_parser"
            - "@expression_converter"

    expression_converter:
        class: Chronis\Service\ExpressionConverterService
        arguments:
            - "@expression_parser"

    expression_parser:
        class: BenTools\NaturalCronExpression\NaturalCronExpressionParser
