parameters:
    version: 0.8.1

services:
    config_parser:
        class: Chronis\Service\ConfigurationParserService

    crontab_generator:
        class: Chronis\Service\CrontabGeneratorService
        arguments:
            - "@config_parser"
            - "@cron_converter"

    cron_converter:
        class: Chronis\Service\CronConverterService
        arguments:
            - "@expression_parser"

    expression_parser:
        class: BenTools\NaturalCronExpression\NaturalCronExpressionParser

    template:
        class: Chronis\Service\TemplateService
